package seatmanager

import (
	"github.com/iotaledger/hive.go/runtime/event"
	"github.com/iotaledger/iota-core/pkg/core/account"
	"github.com/iotaledger/iota-core/pkg/protocol/engine/blocks"
	iotago "github.com/iotaledger/iota.go/v4"
)

type Events struct {
	BlockProcessed             *event.Event1[*blocks.Block]
	OnlineCommitteeSeatAdded   *event.Event2[account.SeatIndex, iotago.AccountID]
	OnlineCommitteeSeatRemoved *event.Event1[account.SeatIndex]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		BlockProcessed:             event.New1[*blocks.Block](),
		OnlineCommitteeSeatAdded:   event.New2[account.SeatIndex, iotago.AccountID](),
		OnlineCommitteeSeatRemoved: event.New1[account.SeatIndex](),
	}
})
