eval "$NETWORK_ENVIRONMENT"

export ANSIBLE_STRATEGY=free
export ANSIBLE_PIPELINING=true
export ANSIBLE_PERSISTENT_CONTROL_PATH_DIR="/tmp/"

ARGS=("$@")
ansible-playbook -u root -i deploy/ansible/hosts/"${1:-feature.yml}" \
  --forks 20 --ssh-common-args "-o ControlMaster=auto -o ControlPersist=5m" \
  --extra-vars \
"customSnapshotUrl=$CUSTOM_SNAPSHOT_URL
defaultSnapshotUrl=$DEFAULT_SNAPSHOT_URL
iota_core_docker_image_repo=$IOTA_CORE_DOCKER_IMAGE_REPO
iota_core_docker_image_tag=$IOTA_CORE_DOCKER_IMAGE_TAG
wireguard_server_private_key=$WIREGUARD_SERVER_PRIVKEY
elkElasticUser=$ELASTIC_USER
elkElasticPassword=$ELASTIC_PASSWORD
grafanaAdminPassword=$GRAFANA_ADMIN_PASSWORD

NODE_01_ACCOUNTID=$NODE_01_ACCOUNTID
NODE_02_ACCOUNTID=$NODE_02_ACCOUNTID
NODE_03_ACCOUNTID=$NODE_03_ACCOUNTID

NODE_01_VALIDATOR_PRIVKEY=$NODE_01_VALIDATOR_PRIVKEY
NODE_02_VALIDATOR_PRIVKEY=$NODE_02_VALIDATOR_PRIVKEY
NODE_03_VALIDATOR_PRIVKEY=$NODE_03_VALIDATOR_PRIVKEY

NODE_01_P2PIDENTITYPRIVATEKEY=$NODE_01_P2PIDENTITYPRIVATEKEY
NODE_02_P2PIDENTITYPRIVATEKEY=$NODE_02_P2PIDENTITYPRIVATEKEY
NODE_03_P2PIDENTITYPRIVATEKEY=$NODE_03_P2PIDENTITYPRIVATEKEY
NODE_04_P2PIDENTITYPRIVATEKEY=$NODE_04_P2PIDENTITYPRIVATEKEY
NODE_05_P2PIDENTITYPRIVATEKEY=$NODE_05_P2PIDENTITYPRIVATEKEY

BLOCKISSUER_PRV_KEY=$BLOCKISSUER_PRV_KEY
FAUCET_PRV_KEY=$FAUCET_PRV_KEY

  ${ARGS[@]:2} deploy/ansible/"${2:-deploy.yml}"
