{
 "title": "Scheduler Metrics",
 "description": "Shows metrics of a single node.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Scheduler metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mana-scaled queue size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (issuer_id) (scheduler_queue_size_per_node_count{instance=~\"$instance\"}/scheduler_mana_per_node{instance=~\"$instance\"}))",
     "legendFormat": "Issuer: {{issuer_id}}"
    }
   ]
  },
  {
   "title": "Scheduling rate",
   "type": "stat",
   "description": "Rate at which scheduler processes blocks from the buffer",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "WU/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_rate{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max buffer size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_max_size{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current buffer size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_size_block_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Scheduled blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_processed_blocks{instance=~\"$instance\", state=\"scheduled\"}"
    }
   ]
  },
  {
   "title": "Dropped blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_processed_blocks{instance=~\"$instance\", state=\"dropped\"}"
    }
   ]
  },
  {
   "title": "Skipped blocks",
   "type": "stat",
   "description": "Blocks skipped by the scheduler, because they were confirmed before. ",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_processed_blocks{instance=~\"$instance\", state=\"skipped\"}"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (issuer_id) (scheduler_queue_size_per_node_count{instance=~\"$instance\"}))",
     "legendFormat": "Issuer: {{issuer_id}}"
    }
   ]
  },
  {
   "title": "All blocks count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_processed_blocks{instance=~\"$instance\", state=\"enqueued\"}"
    }
   ]
  },
  {
   "title": "Unready blocks count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_size_block_total{instance=~\"$instance\"} - scheduler_buffer_ready_block_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Ready blocks count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_ready_block_total{instance=~\"$instance\"}"
    }
   ]
  }
 ]
}