{
 "title": "Global Slots View",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Slot metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks per slot $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "slots_total_blocks\n", "legendFormat": "__auto" },
    { "expr": "slots_accepted_blocks", "legendFormat": "__auto" },
    { "expr": "slots_orphaned_blocks\n", "legendFormat": "__auto" },
    { "expr": "slots_invalid_blocks\n", "legendFormat": "__auto" },
    {
     "expr": "slots_subjectively_invalid_blocks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per slot $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "slots_orphaned_attachments", "legendFormat": "__auto" },
    { "expr": "slots_total_attachments\n", "legendFormat": "__auto" },
    { "expr": "slots_rejected_attachments", "legendFormat": "__auto" },
    { "expr": "slots_accepted_attachments\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Conflicts per slot $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "repeat": "instance",
   "targets": [
    { "expr": "slots_created_conflicts", "legendFormat": "__auto" },
    { "expr": "slots_accepted_conflicts\n", "legendFormat": "__auto" },
    { "expr": "slots_rejected_conflicts\n", "legendFormat": "__auto" },
    {
     "expr": "slots_not_conflicting_conflicts\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}