package core

import (
	"github.com/iotaledger/hive.go/crypto/identity"
	"github.com/iotaledger/hive.go/runtime/event"
	"github.com/iotaledger/iota-core/pkg/model"
	iotago "github.com/iotaledger/iota.go/v4"
)

type Events struct {
	BlockReceived                 *event.Event2[*model.Block, identity.ID]
	BlockRequestReceived          *event.Event2[iotago.BlockID, identity.ID]
	SlotCommitmentReceived        *event.Event2[*iotago.Commitment, identity.ID]
	SlotCommitmentRequestReceived *event.Event2[iotago.CommitmentID, identity.ID]
	AttestationsReceived          *event.Event1[*AttestationsReceivedEvent]
	AttestationsRequestReceived   *event.Event1[*AttestationsRequestReceivedEvent]
	Error                         *event.Event2[error, identity.ID]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		BlockReceived:                 event.New2[*model.Block, identity.ID](),
		BlockRequestReceived:          event.New2[iotago.BlockID, identity.ID](),
		SlotCommitmentReceived:        event.New2[*iotago.Commitment, identity.ID](),
		SlotCommitmentRequestReceived: event.New2[iotago.CommitmentID, identity.ID](),
		AttestationsReceived:          event.New1[*AttestationsReceivedEvent](),
		AttestationsRequestReceived:   event.New1[*AttestationsRequestReceivedEvent](),
		Error:                         event.New2[error, identity.ID](),
	}
})

type AttestationsReceivedEvent struct {
	Commitment *iotago.Commitment
	BlockIDs   iotago.BlockIDs
	//Attestations *orderedmap.OrderedMap[iotago.SlotIndex, *advancedset.AdvancedSet[*notarization.Attestation]]
	Source identity.ID
}

type AttestationsRequestReceivedEvent struct {
	Commitment *iotago.Commitment
	EndIndex   iotago.SlotIndex
	Source     identity.ID
}
