package core

import (
	"github.com/libp2p/go-libp2p/core/peer"

	"github.com/iotaledger/hive.go/runtime/event"
	"github.com/iotaledger/iota-core/pkg/model"
	iotago "github.com/iotaledger/iota.go/v4"
	"github.com/iotaledger/iota.go/v4/merklehasher"
)

type Events struct {
	BlockReceived                 *event.Event2[*model.Block, peer.ID]
	BlockRequestReceived          *event.Event2[iotago.BlockID, peer.ID]
	SlotCommitmentReceived        *event.Event2[*model.Commitment, peer.ID]
	SlotCommitmentRequestReceived *event.Event2[iotago.CommitmentID, peer.ID]
	AttestationsReceived          *event.Event4[*model.Commitment, []*iotago.Attestation, *merklehasher.Proof[iotago.Identifier], peer.ID]
	AttestationsRequestReceived   *event.Event2[iotago.CommitmentID, peer.ID]
	WarpSyncRequestReceived       *event.Event2[iotago.CommitmentID, peer.ID]
	WarpSyncResponseReceived      *event.Event4[iotago.CommitmentID, iotago.BlockIDs, *merklehasher.Proof[iotago.Identifier], peer.ID]
	Error                         *event.Event2[error, peer.ID]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		BlockReceived:                 event.New2[*model.Block, peer.ID](),
		BlockRequestReceived:          event.New2[iotago.BlockID, peer.ID](),
		SlotCommitmentReceived:        event.New2[*model.Commitment, peer.ID](),
		SlotCommitmentRequestReceived: event.New2[iotago.CommitmentID, peer.ID](),
		AttestationsReceived:          event.New4[*model.Commitment, []*iotago.Attestation, *merklehasher.Proof[iotago.Identifier], peer.ID](),
		AttestationsRequestReceived:   event.New2[iotago.CommitmentID, peer.ID](),
		WarpSyncRequestReceived:       event.New2[iotago.CommitmentID, peer.ID](),
		WarpSyncResponseReceived:      event.New4[iotago.CommitmentID, iotago.BlockIDs, *merklehasher.Proof[iotago.Identifier], peer.ID](),
		Error:                         event.New2[error, peer.ID](),
	}
})
