{
 "title": "Commitments Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last commitmed slot $instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(commitments_latest{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(commitments_finalized{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Commitee Seats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    { "expr": "account_active_seats", "legendFormat": "__auto" }
   ]
  },
  { "title": "Slot Commitments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Commitments $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 15 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "commitments_latest{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Slot Commitment - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Details $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "commitments_accepted_blocks{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "commitments_accepted_transactions{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}