{
 "title": "Global Nodes View",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last commitmed slot $instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 1 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(commitments_latest{}) by (slot, instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(commitments_finalized{}) by (slot, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Commitee Seats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    { "expr": "account_active_seats", "legendFormat": "__auto" }
   ]
  },
  { "title": "Slot Commitments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Commitments $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 15 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "SI" } },
   "targets": [
    {
     "expr": "max(commitments_latest{instance=\"$instance\", slot!=\"0\"}) by (commitment, slot)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Missing commitments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Number of missing commitments by node",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "commitments_missing_requested_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of received missing commitments ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "commitments_missing_received_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}