{
 "title": "iota-core Local Metrics",
 "description": "Shows metrics of a single node.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "NodeID", "label": "Node Identity", "query": { "query": "label_values(nodeID)" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "iota-core",
   "type": "stat",
   "description": "Version number of node software.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_app{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Node Identity",
   "type": "stat",
   "description": "Shortened version of the public key of the node.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_app{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Shows the time elapsed since the start of the node.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Synced",
   "type": "stat",
   "description": "Describes if the node is in synced state.",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_sync_status{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total BPS",
   "type": "stat",
   "description": "Aggregated BPS for all block types in the communication layer.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "BPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(tangle_blocks_per_component_total{component=\"Attached\",instance=\"$instance\"}[5m])",
     "legendFormat": "Total BPS"
    }
   ]
  },
  {
   "title": "Access Mana (Current)",
   "type": "stat",
   "description": "Amount of access mana this node has",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "si: m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mana_access_per_node{instance=\"$instance\",nodeID=\"$NodeID\"}"
    }
   ]
  },
  {
   "title": "Consensus Mana (Current)",
   "type": "stat",
   "description": "Amount of consensus mana this node has.",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "si: m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mana_consensus_per_node{instance=\"$instance\",nodeID=\"$NodeID\"}"
    }
   ]
  },
  {
   "title": "Total Database Size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_size_bytes{instance=\"$instance\"}) /1024/1024"
    }
   ]
  },
  {
   "title": "Permanent DB Size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_size_bytes{type=\"storage_permanent\", instance=\"$instance\"}) /1024/1024"
    }
   ]
  },
  {
   "title": "Prunable DB size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_size_bytes{type=\"storage_prunable\", instance=\"$instance\"}) /1024/1024"
    }
   ]
  },
  {
   "title": "Retainer DB size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_size_bytes{instance=\"$instance\", type=\"retainer\"}) /1024/1024"
    }
   ]
  },
  {
   "title": "BPS, Autopeering, Traffic, Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Per Second Per Type",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "BPS" }
     ],
     "targets": [
      {
       "expr": "irate(tangle_block_per_type_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Block Per Second {{block_type}}"
      }
     ]
    },
    {
     "title": "Block Per Second Per Component",
     "type": "graph",
     "gridPos": { "h": 11, "w": 13, "x": 11, "y": 4 },
     "yaxes": [
      { "format": "BPS" }
     ],
     "targets": [
      {
       "expr": "irate(tangle_blocks_per_component_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{component}} BPS"
      }
     ]
    },
    {
     "title": "Tips",
     "type": "graph",
     "description": "Shows tips in block and value layer.",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tangle_tips_count{instance=\"$instance\"}",
       "legendFormat": "Block Layer Tips"
      }
     ]
    },
    {
     "title": "Autopeering Neighbor Distance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Distance" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(autopeering_distance{instance=\"$instance\"}[$__range])",
       "legendFormat": "Average"
      },
      {
       "expr": "max_over_time(autopeering_distance{instance=\"$instance\"}[$__range])",
       "legendFormat": "Max"
      },
      {
       "expr": "min_over_time(autopeering_distance{instance=\"$instance\"}[$__range])",
       "legendFormat": "Min"
      }
     ]
    },
    {
     "title": "Current Neighbors",
     "type": "stat",
     "description": "Number of currently connected neighbors.",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "autopeering_neighbor_connections_total{instance=\"$instance\"} - autopeering_neighbor_drop_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "AvgNeighbor Connection Lifetime",
     "type": "stat",
     "description": "Calculated for each dropped neighbor.",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "autopeering_neighbor_connection_lifetime_seconds_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "New Neighbor Connections",
     "type": "stat",
     "description": "Amount of newly registered neighbor connections.",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "autopeering_neighbor_connections_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Dropped Neighbor Connections",
     "type": "stat",
     "description": "Amount of neighbor connections dropped.",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "autopeering_neighbor_drop_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Solidifier-requested blocks per second",
     "type": "graph",
     "description": "Number of blocks requested through solidification. ",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(tangle_missing_block_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Solidifier-requested blocks"
      }
     ]
    },
    {
     "title": "Solidifier-requested blocks total",
     "type": "graph",
     "description": "Number of blocks requested through solidification. ",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tangle_missing_block_total{instance=\"$instance\"}",
       "legendFormat": "Solidifier-requested blocks"
      }
     ]
    },
    {
     "title": "Analysis",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 11, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "traffic_analysis_outbound_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Gossip TX",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 13, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "traffic_gossip_outbound_packets{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Gossip RX",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "traffic_gossip_inbound_packets{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Autopeering TX",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "autopeering_traffic_outbound_total_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Autopeering RX",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "autopeering_traffic_inbound_total_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(traffic_analysis_outbound_bytes{instance=\"$instance\"}[1m])",
       "legendFormat": "Analysis TX"
      },
      {
       "expr": "irate(autopeering_traffic_inbound_total_bytes{instance=\"$instance\"}[1m])",
       "legendFormat": "Autopeering RX"
      },
      {
       "expr": "irate(autopeering_traffic_outbound_total_bytes{instance=\"$instance\"}[1m])",
       "legendFormat": "Autopeering TX"
      },
      {
       "expr": "irate(traffic_fpc_inbound_bytes{instance=\"$instance\"}[1m])",
       "legendFormat": "FPC RX"
      },
      {
       "expr": "irate(traffic_fpc_outbound_bytes{instance=\"$instance\"}[1m])",
       "legendFormat": "FPC TX"
      },
      {
       "expr": "irate(traffic_gossip_inbound_packets{instance=\"$instance\"}[1m])",
       "legendFormat": "Gossip RX"
      },
      {
       "expr": "irate(traffic_gossip_outbound_packets{instance=\"$instance\"}[1m])",
       "legendFormat": "Gossip Tx"
      }
     ]
    },
    {
     "title": "Missing Blocks",
     "type": "graph",
     "description": "Number of blocks in missingBlockStore. These are the block the node knows it doesn't have and tries to requests them.",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tangle_missing_block_total{instance=\"$instance\"}",
       "legendFormat": "Missing Blocks"
      }
     ]
    },
    {
     "title": "Blocks in Database",
     "type": "graph",
     "description": "Describes the amount of total, solid and not solid blocks in the node's database.",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tangle_blocks_per_component_total{component=\"Solidified\",instance=\"$instance\"}",
       "legendFormat": "Solid Blocks in DB"
      },
      {
       "expr": "tangle_blocks_per_component_total{component=\"Store\",instance=\"$instance\"} - tangle_blocks_per_component_total{component=\"Solidified\",instance=\"$instance\"}",
       "legendFormat": "Not Solid Blocks in DB"
      },
      {
       "expr": "tangle_blocks_per_component_total{component=\"Store\",instance=\"$instance\"}",
       "legendFormat": "Total Blocks in DB"
      }
     ]
    },
    {
     "title": "Block Request Queue Size",
     "type": "graph",
     "description": "Number of blocks currently requested by the block tangle.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tangle_request_queue_size{instance=\"$instance\"}",
       "legendFormat": "Block Request Queue Size"
      }
     ]
    },
    {
     "title": "Average Solidification Time",
     "type": "graph",
     "description": "Average time it takes to solidify blocks.",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(tangle_block_total_time_since_received{component=\"Solidified\",instance=\"$instance\"}[5m])/rate(tangle_blocks_per_component_total{component=\"Solidified\",instance=\"$instance\"}[5m])",
       "legendFormat": "Avg Solidification Time"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Mana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Mana",
     "type": "stat",
     "description": "Amount of access mana this node has",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_access_per_node{instance=\"$instance\",nodeID=\"$NodeID\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Mana Percentile",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_node_percentile{instance=\"$instance\",type=\"access\"}",
       "legendFormat": "Access"
      },
      {
       "expr": "mana_node_percentile{instance=\"$instance\",type=\"consensus\"}",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Average Mana",
     "type": "stat",
     "description": "Average mana of a node i nthe network.",
     "gridPos": { "h": 3, "w": 4, "x": 7, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(mana_access_per_node{instance=\"$instance\"})",
       "legendFormat": "Access"
      },
      {
       "expr": "avg(mana_consensus_per_node{instance=\"$instance\"})",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Standard Deviation of Mana",
     "type": "stat",
     "description": "Standard deviation of mana of nodes in the network.",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stddev(mana_access_per_node{instance=\"$instance\"})",
       "legendFormat": "Access"
      },
      {
       "expr": "stddev(mana_consensus_per_node{instance=\"$instance\"})",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Average neighbours mana",
     "type": "stat",
     "description": "Average access and consensus mana of a nodes nneighbours.",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_neighbors{instance=\"$instance\"}",
       "legendFormat": "Access"
      },
      {
       "expr": "mana_neighbors{instance=\"$instance\"}",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Total Mana",
     "type": "graph",
     "description": "Total Access & Consensus Mana In the network.",
     "gridPos": { "h": 15, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "sum(mana_access_per_node{instance=\"$instance\"})",
       "legendFormat": "Total Access Mana In Network"
      },
      {
       "expr": "sum(mana_consensus_per_node{instance=\"$instance\"})",
       "legendFormat": "Total Consensus Mana In Network"
      }
     ]
    },
    {
     "title": "Access Mana Distribution In Network",
     "type": "graph",
     "description": "Histogram of access mana of nodes.",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "Number of Nodes" }
     ],
     "targets": [
      { "expr": "mana_access_per_node{}" }
     ]
    },
    {
     "title": "Consensus Mana Distribution in Network",
     "type": "graph",
     "description": "Histogram of consensus mana of nodes.",
     "gridPos": { "h": 12, "w": 9, "x": 9, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "Number of Nodes" }
     ],
     "targets": [
      { "expr": "mana_consensus_per_node{}" }
     ]
    },
    {
     "title": "Access Mana",
     "type": "graph",
     "description": "Amount of access mana this node has",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_access_per_node{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Network Wide Access Mana",
     "type": "graph",
     "description": "Amount of access mana of nodes in the network.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_access_per_node{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Access Mana Allocation",
     "type": "piechart",
     "description": "Allocation of access mana of nodes in the network.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_access_per_node{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Consensus Mana",
     "type": "graph",
     "description": "Amount of consensus mana this node has.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_consensus_per_node{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Network Wide Consensus Mana",
     "type": "graph",
     "description": "Amount of consensus mana of nodes in the network.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_consensus_per_node{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Consensus Mana Allocation",
     "type": "piechart",
     "description": "Allocation of consensus mana of nodes in the network.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_consensus_per_node{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Mana Percentile Development",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "mana_node_percentile{instance=\"$instance\",type=\"access\"}",
       "legendFormat": "Access Percentile"
      },
      {
       "expr": "mana_node_percentile{instance=\"$instance\",type=\"consensus\"}",
       "legendFormat": "Consensus Percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "OTV metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block finalization time",
     "type": "graph",
     "description": "Indicates an average time it takes for a block to be finalized since it is received by the node.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(conflict_resolution_time_seconds_total{instance=\"$instance\"}[1m]) / irate(conflict_resolved_total{instance=\"$instance\"}[1m])",
       "legendFormat": "{{blockType}} avg. finalization time"
      }
     ]
    },
    {
     "title": "Conflict finalization time",
     "type": "graph",
     "description": "Indicates an average time it takes for a block to be finalized since it is received by the node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(conflict_resolution_time_seconds_total{instance=\"$instance\"}[30s]) / rate(conflict_resolved_total{instance=\"$instance\"}[30s])",
       "legendFormat": "Average conflict confirmation time"
      }
     ]
    },
    {
     "title": "Average number of parents by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(tangle_parent_per_type_total{instance=\"$instance\"}[1m])) by (type,instance) / on(instance) group_left() sum(irate(tangle_accepted_blocks_count{instance=\"$instance\"}[1m])) by (instance)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total number of conflicts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conflict_created_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total number of unresolved conflicts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conflict_created_total{instance=\"$instance\"} - conflict_resolved_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total number of finalized conflicts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conflict_resolved_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total number of confirmed conflicts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "conflict_resolved_total{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mana-scaled queue size",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(15, sum by (node_id) (scheduler_queue_size_per_node_bytes{instance=\"$instance\"}/scheduler_mana_per_node{instance=\"$instance\"}))",
       "legendFormat": "Node: {{node_id}}"
      }
     ]
    },
    {
     "title": "Scheduling rate",
     "type": "stat",
     "description": "Rate at which scheduler processes blocks from the buffer",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scheduler_rate{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Scheduled blocks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tangle_blocks_per_component_total{component=\"Scheduled\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Skipped blocks",
     "type": "stat",
     "description": "Blocks skipped by the scheduler, because they were confirmed before. ",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tangle_blocks_per_component_total{component=\"SchedulerSkipped\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max buffer size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "scheduler_buffer_max_size{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Dropped blocks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tangle_blocks_per_component_total{component=\"SchedulerDropped\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Own scheduler deficit",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scheduler_deficit{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Queue size",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(15, sum by (node_id) (scheduler_queue_size_per_node_bytes{instance=\"$instance\"}))",
       "legendFormat": "Node: {{node_id}}"
      }
     ]
    },
    {
     "title": "Current buffer size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "scheduler_buffer_size_bytes_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "All blocks count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scheduler_buffer_size_bytes_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Rate-setter estimate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratesetter_estimate{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Rate-setter buffer size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratesetter_buffer_size{instance=\"$instance\"}",
       "legendFormat": "Own ratesetter queue size"
      },
      {
       "expr": "scheduler_queue_size_per_node_bytes{node_id=\"$NodeID\",instance=\"$instance\"}",
       "legendFormat": "Own scheduler queue size"
      }
     ]
    },
    {
     "title": "Unready blocks count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "scheduler_buffer_size_bytes_total{instance=\"$instance\"} - scheduler_buffer_ready_block_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Ready blocks count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scheduler_buffer_ready_block_total{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Rate-setter own rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratesetter_own_rate{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Orphaned blocks count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "blocks" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tangle_blocks_orphaned_total{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "Workerpools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workerpool_workers{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "workerpool_tasks_pending{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}