package notarization

import (
	"github.com/iotaledger/hive.go/ads"
	"github.com/iotaledger/hive.go/runtime/event"
	"github.com/iotaledger/iota-core/pkg/model"
	iotago "github.com/iotaledger/iota.go/v4"
)

// Events is a container that acts as a dictionary for the events of the notarization manager.
type Events struct {
	SlotCommitted *event.Event1[*SlotCommittedDetails]
	Error         *event.Event1[error]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (self *Events) {
	return &Events{
		SlotCommitted: event.New1[*SlotCommittedDetails](),
		Error:         event.New1[error](),
	}
})

// SlotCommittedDetails contains the details of a committed slot.
type SlotCommittedDetails struct {
	Commitment             *model.Commitment
	RatifiedAcceptedBlocks *ads.Set[iotago.BlockID, *iotago.BlockID]
	ActiveValidatorsCount  int
}
