package blockgadget

import (
	"github.com/iotaledger/hive.go/runtime/event"
	"github.com/iotaledger/iota-core/pkg/protocol/engine/blocks"
)

type Events struct {
	BlockPreAccepted  *event.Event1[*blocks.Block]
	BlockPreConfirmed *event.Event1[*blocks.Block]
	BlockAccepted     *event.Event1[*blocks.Block]
	BlockConfirmed    *event.Event1[*blocks.Block]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		BlockPreAccepted:  event.New1[*blocks.Block](),
		BlockPreConfirmed: event.New1[*blocks.Block](),
		BlockAccepted:     event.New1[*blocks.Block](),
		BlockConfirmed:    event.New1[*blocks.Block](),
	}
})
