package blockgadget

import (
	"github.com/iotaledger/hive.go/runtime/event"
)

type Events struct {
	BlockAccepted  *event.Event1[*Block]
	BlockConfirmed *event.Event1[*Block]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		BlockAccepted:  event.New1[*Block](),
		BlockConfirmed: event.New1[*Block](),
	}
})
