package ledger

import (
	"github.com/iotaledger/hive.go/runtime/event"
)

type Events struct {
	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{}
})
