package sybilprotection

import (
	"github.com/iotaledger/hive.go/runtime/event"
	iotago "github.com/iotaledger/iota.go/v4"
)

type Events struct {
	OnlineCommitteeAccountAdded   *event.Event1[iotago.AccountID]
	OnlineCommitteeAccountRemoved *event.Event1[iotago.AccountID]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		OnlineCommitteeAccountAdded:   event.New1[iotago.AccountID](),
		OnlineCommitteeAccountRemoved: event.New1[iotago.AccountID](),
	}
})
