package booker

import (
	"github.com/iotaledger/hive.go/runtime/event"
)

type Events struct {
	BlockBooked *event.Event1[*Block]
	Error       *event.Event1[error]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		BlockBooked: event.New1[*Block](),
		Error:       event.New1[error](),
	}
})
